// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions androidtest = FirebaseOptions(
    apiKey: 'AIzaSyDtj4sERAq_eA0_ns4cL_vawwo5mGs-mAI',
    appId: '1:231474097785:android:c47bc9d6e7ea8289d5eea8',
    messagingSenderId: '231474097785',
    projectId: 'pushnotificatn-af7d6',
    storageBucket: 'pushnotificatn-af7d6.appspot.com',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuZ2VPJ6b-PQqZuXl0bLjcIhIl8XPIr8',
    appId: '1:565082619746:android:b71b244d3ee8c23945b63b',
    messagingSenderId: '565082619746',
    projectId: 'pearld3-apps',
    storageBucket: 'pearld3-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBj0ITPFu-zkvzLeCuYsmPJIlkyMKs4Q',
    appId: '1:231474097785:ios:a003d429bd9975aed5eea8',
    messagingSenderId: '231474097785',
    projectId: 'pushnotificatn-af7d6',
    storageBucket: 'pushnotificatn-af7d6.appspot.com',
    iosClientId: '231474097785-phuurirj888s9k5tmufd7p9fheq3j2bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tvApp',
  );
}
